spring:
  datasource:
    url: jdbc:h2:mem:testdb # in memory
#    url: jdbc:h2:file:/data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # tworzy tabele w bazie danych
#    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
#  sql:
#    init:
#      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
#  batch:
#    jdbc:
#      initialize-schema: always
